<template>
<div>
  <b-carousel
    id="carousel-fade"
    style="text-shadow: 0px 0px 2px #000"
    fade
    indicators
    img-width="1024"
    img-height="480"
  >
    <b-carousel-slide
      img-src="../img/1.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      img-src="../img/2.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      img-src="../img/3.jpg"
    ></b-carousel-slide>
        <b-carousel-slide
      img-src="../img/4.jpg"
    ></b-carousel-slide>
  </b-carousel>
</div>
</template>